services:
  db:
    image: postgres:14.7
    volumes:
      - db_data:/data/pgdata
      - ./init:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      - POSTGRES_USER=dockeruser1
      - POSTGRES_PASSWORD=dockerpassword1
      - PGDATA=/data/pgdata
    expose:
      - 5432
    ports:
      - 5432:5432        
  adminer:
    image: adminer
    restart: always
    ports: 
    - 8080:8080
  webapp:
    image: webapp
    environment:
       - ASPNETCORE_ENVIRONMENT=Development
    ports:
    - 8081:80
volumes:
  db_data:
